[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sdl2 = { version = "0.36.0" }

[profile.release]
lto = true
debug = false
opt-level = 3
strip = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
